[package]
name = "tauri-plugin-redterm-android-paste"
version = "0.1.0"
edition = "2021"
links = "tauri-plugin-redterm-android-paste"
build = "build.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", default-features = false }

[build-dependencies]
tauri-plugin = { version = "2.4", features = ["build"] }
