export interface ThemeColors {
  bgPrimary: string;
  bgSecondary: string;
  bgTertiary: string;
  bgHover: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  accentPrimary: string;
  accentHover: string;
  accentMuted: string;
  statusSuccess: string;
  statusWarning: string;
  statusError: string;
  borderPrimary: string;
  borderSecondary: string;
  terminalBg: string;
  terminalFg: string;
  terminalCursor: string;
  terminalSelection: string;
}

export interface ThemeDefinition {
  id: string;
  name: string;
  colors: ThemeColors;
}

function linearChannel(channel: number): number {
  const normalized = channel / 255;
  return normalized <= 0.04045
    ? normalized / 12.92
    : ((normalized + 0.055) / 1.055) ** 2.4;
}

export function isLightTheme(theme: ThemeDefinition): boolean {
  const value = Number.parseInt(theme.colors.terminalBg.slice(1), 16);
  const luminance =
    0.2126 * linearChannel((value >> 16) & 0xff) +
    0.7152 * linearChannel((value >> 8) & 0xff) +
    0.0722 * linearChannel(value & 0xff);
  return luminance > 0.5;
}

export const THEMES: ThemeDefinition[] = [
  {
    id: "coder-red",
    name: "Coder Red",
    colors: {
      bgPrimary: "#1a0f0f",
      bgSecondary: "#2d1515",
      bgTertiary: "#3d2020",
      bgHover: "#4a2525",
      textPrimary: "#e8d4d4",
      textSecondary: "#c4a8a8",
      textMuted: "#8a6060",
      accentPrimary: "#ff6b6b",
      accentHover: "#ff8585",
      accentMuted: "#cc5555",
      statusSuccess: "#98c379",
      statusWarning: "#e5c07b",
      statusError: "#f38ba8",
      borderPrimary: "#2d1515",
      borderSecondary: "#3d2020",
      terminalBg: "#1a0f0f",
      terminalFg: "#e8d4d4",
      terminalCursor: "#ff6b6b",
      terminalSelection: "#4a2525",
    },
  },
  {
    id: "dark-blue",
    name: "Dark Blue",
    colors: {
      bgPrimary: "#0f1520",
      bgSecondary: "#152035",
      bgTertiary: "#1f2d45",
      bgHover: "#253550",
      textPrimary: "#d4dce8",
      textSecondary: "#a8b8c8",
      textMuted: "#607088",
      accentPrimary: "#6b9fff",
      accentHover: "#85b0ff",
      accentMuted: "#5580cc",
      statusSuccess: "#98c379",
      statusWarning: "#e5c07b",
      statusError: "#f38ba8",
      borderPrimary: "#152035",
      borderSecondary: "#1f2d45",
      terminalBg: "#0f1520",
      terminalFg: "#d4dce8",
      terminalCursor: "#6b9fff",
      terminalSelection: "#253550",
    },
  },
  {
    id: "monokai",
    name: "Monokai",
    colors: {
      bgPrimary: "#272822",
      bgSecondary: "#3e3d32",
      bgTertiary: "#49483e",
      bgHover: "#575648",
      textPrimary: "#f8f8f2",
      textSecondary: "#cfcfc2",
      textMuted: "#75715e",
      accentPrimary: "#f92672",
      accentHover: "#ff4088",
      accentMuted: "#c41858",
      statusSuccess: "#a6e22e",
      statusWarning: "#e6db74",
      statusError: "#f92672",
      borderPrimary: "#3e3d32",
      borderSecondary: "#49483e",
      terminalBg: "#272822",
      terminalFg: "#f8f8f2",
      terminalCursor: "#f8f8f0",
      terminalSelection: "#49483e",
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    colors: {
      bgPrimary: "#002b36",
      bgSecondary: "#073642",
      bgTertiary: "#0a4050",
      bgHover: "#0d4d5e",
      textPrimary: "#839496",
      textSecondary: "#657b83",
      textMuted: "#586e75",
      accentPrimary: "#268bd2",
      accentHover: "#2e9ee6",
      accentMuted: "#1e6fa5",
      statusSuccess: "#859900",
      statusWarning: "#b58900",
      statusError: "#dc322f",
      borderPrimary: "#073642",
      borderSecondary: "#0a4050",
      terminalBg: "#002b36",
      terminalFg: "#839496",
      terminalCursor: "#268bd2",
      terminalSelection: "#073642",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    colors: {
      bgPrimary: "#282a36",
      bgSecondary: "#343746",
      bgTertiary: "#424456",
      bgHover: "#4d4f66",
      textPrimary: "#f8f8f2",
      textSecondary: "#c0c0d0",
      textMuted: "#6272a4",
      accentPrimary: "#bd93f9",
      accentHover: "#caa4ff",
      accentMuted: "#9b6fd6",
      statusSuccess: "#50fa7b",
      statusWarning: "#f1fa8c",
      statusError: "#ff5555",
      borderPrimary: "#343746",
      borderSecondary: "#424456",
      terminalBg: "#282a36",
      terminalFg: "#f8f8f2",
      terminalCursor: "#f8f8f2",
      terminalSelection: "#44475a",
    },
  },
  {
    id: "nord",
    name: "Nord",
    colors: {
      bgPrimary: "#2e3440",
      bgSecondary: "#3b4252",
      bgTertiary: "#434c5e",
      bgHover: "#4c566a",
      textPrimary: "#eceff4",
      textSecondary: "#d8dee9",
      textMuted: "#616e88",
      accentPrimary: "#88c0d0",
      accentHover: "#8fbcbb",
      accentMuted: "#6ba0b0",
      statusSuccess: "#a3be8c",
      statusWarning: "#ebcb8b",
      statusError: "#bf616a",
      borderPrimary: "#3b4252",
      borderSecondary: "#434c5e",
      terminalBg: "#2e3440",
      terminalFg: "#eceff4",
      terminalCursor: "#d8dee9",
      terminalSelection: "#434c5e",
    },
  },
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    colors: {
      bgPrimary: "#282828",
      bgSecondary: "#3c3836",
      bgTertiary: "#504945",
      bgHover: "#665c54",
      textPrimary: "#ebdbb2",
      textSecondary: "#d5c4a1",
      textMuted: "#928374",
      accentPrimary: "#fe8019",
      accentHover: "#fabd2f",
      accentMuted: "#d65d0e",
      statusSuccess: "#b8bb26",
      statusWarning: "#fabd2f",
      statusError: "#fb4934",
      borderPrimary: "#3c3836",
      borderSecondary: "#504945",
      terminalBg: "#282828",
      terminalFg: "#ebdbb2",
      terminalCursor: "#ebdbb2",
      terminalSelection: "#504945",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    colors: {
      bgPrimary: "#1a1b26",
      bgSecondary: "#24283b",
      bgTertiary: "#2f3348",
      bgHover: "#3b3f55",
      textPrimary: "#c0caf5",
      textSecondary: "#a9b1d6",
      textMuted: "#565f89",
      accentPrimary: "#7aa2f7",
      accentHover: "#89b4fa",
      accentMuted: "#5d7fc7",
      statusSuccess: "#9ece6a",
      statusWarning: "#e0af68",
      statusError: "#f7768e",
      borderPrimary: "#24283b",
      borderSecondary: "#2f3348",
      terminalBg: "#1a1b26",
      terminalFg: "#c0caf5",
      terminalCursor: "#c0caf5",
      terminalSelection: "#33467c",
    },
  },
  {
    id: "one-dark",
    name: "One Dark",
    colors: {
      bgPrimary: "#282c34",
      bgSecondary: "#2c313a",
      bgTertiary: "#353b45",
      bgHover: "#3e4452",
      textPrimary: "#abb2bf",
      textSecondary: "#9da5b4",
      textMuted: "#5c6370",
      accentPrimary: "#61afef",
      accentHover: "#74bfff",
      accentMuted: "#4d8bc0",
      statusSuccess: "#98c379",
      statusWarning: "#e5c07b",
      statusError: "#e06c75",
      borderPrimary: "#2c313a",
      borderSecondary: "#353b45",
      terminalBg: "#282c34",
      terminalFg: "#abb2bf",
      terminalCursor: "#528bff",
      terminalSelection: "#3e4452",
    },
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    colors: {
      bgPrimary: "#1e1e2e",
      bgSecondary: "#313244",
      bgTertiary: "#45475a",
      bgHover: "#585b70",
      textPrimary: "#cdd6f4",
      textSecondary: "#bac2de",
      textMuted: "#6c7086",
      accentPrimary: "#cba6f7",
      accentHover: "#d4b8fa",
      accentMuted: "#a280cc",
      statusSuccess: "#a6e3a1",
      statusWarning: "#f9e2af",
      statusError: "#f38ba8",
      borderPrimary: "#313244",
      borderSecondary: "#45475a",
      terminalBg: "#1e1e2e",
      terminalFg: "#cdd6f4",
      terminalCursor: "#f5e0dc",
      terminalSelection: "#45475a",
    },
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    colors: {
      bgPrimary: "#fdf6e3",
      bgSecondary: "#eee8d5",
      bgTertiary: "#e0daca",
      bgHover: "#d6d0c0",
      textPrimary: "#657b83",
      textSecondary: "#586e75",
      textMuted: "#93a1a1",
      accentPrimary: "#268bd2",
      accentHover: "#2e9ee6",
      accentMuted: "#1e6fa5",
      statusSuccess: "#859900",
      statusWarning: "#b58900",
      statusError: "#dc322f",
      borderPrimary: "#eee8d5",
      borderSecondary: "#e0daca",
      terminalBg: "#fdf6e3",
      terminalFg: "#657b83",
      terminalCursor: "#268bd2",
      terminalSelection: "#eee8d5",
    },
  },
  {
    id: "github-light",
    name: "GitHub Light",
    colors: {
      bgPrimary: "#ffffff",
      bgSecondary: "#f6f8fa",
      bgTertiary: "#e1e4e8",
      bgHover: "#d1d5da",
      textPrimary: "#24292e",
      textSecondary: "#586069",
      textMuted: "#959da5",
      accentPrimary: "#0366d6",
      accentHover: "#0451a5",
      accentMuted: "#005cc5",
      statusSuccess: "#28a745",
      statusWarning: "#dbab09",
      statusError: "#d73a49",
      borderPrimary: "#e1e4e8",
      borderSecondary: "#d1d5da",
      terminalBg: "#ffffff",
      terminalFg: "#24292e",
      terminalCursor: "#0366d6",
      terminalSelection: "#c8e1ff",
    },
  },
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    colors: {
      bgPrimary: "#eff1f5",
      bgSecondary: "#e6e9ef",
      bgTertiary: "#dce0e8",
      bgHover: "#ccd0da",
      textPrimary: "#4c4f69",
      textSecondary: "#5c5f77",
      textMuted: "#9ca0b0",
      accentPrimary: "#8839ef",
      accentHover: "#9c4dff",
      accentMuted: "#7030c0",
      statusSuccess: "#40a02b",
      statusWarning: "#df8e1d",
      statusError: "#d20f39",
      borderPrimary: "#e6e9ef",
      borderSecondary: "#dce0e8",
      terminalBg: "#eff1f5",
      terminalFg: "#4c4f69",
      terminalCursor: "#dc8a78",
      terminalSelection: "#dce0e8",
    },
  },
  {
    id: "one-light",
    name: "One Light",
    colors: {
      bgPrimary: "#fafafa",
      bgSecondary: "#f0f0f0",
      bgTertiary: "#e5e5e6",
      bgHover: "#dbdbdc",
      textPrimary: "#383a42",
      textSecondary: "#4f525e",
      textMuted: "#a0a1a7",
      accentPrimary: "#4078f2",
      accentHover: "#5089ff",
      accentMuted: "#3060c0",
      statusSuccess: "#50a14f",
      statusWarning: "#c18401",
      statusError: "#e45649",
      borderPrimary: "#e5e5e6",
      borderSecondary: "#dbdbdc",
      terminalBg: "#fafafa",
      terminalFg: "#383a42",
      terminalCursor: "#526fff",
      terminalSelection: "#e5e5e6",
    },
  },
  {
    id: "nord-light",
    name: "Nord Light",
    colors: {
      bgPrimary: "#eceff4",
      bgSecondary: "#e5e9f0",
      bgTertiary: "#d8dee9",
      bgHover: "#c8ced9",
      textPrimary: "#2e3440",
      textSecondary: "#3b4252",
      textMuted: "#7b88a1",
      accentPrimary: "#5e81ac",
      accentHover: "#81a1c1",
      accentMuted: "#4c6a8f",
      statusSuccess: "#a3be8c",
      statusWarning: "#ebcb8b",
      statusError: "#bf616a",
      borderPrimary: "#d8dee9",
      borderSecondary: "#c8ced9",
      terminalBg: "#eceff4",
      terminalFg: "#2e3440",
      terminalCursor: "#5e81ac",
      terminalSelection: "#d8dee9",
    },
  },
  {
    id: "rose-pine-dawn",
    name: "Rosé Pine Dawn",
    colors: {
      bgPrimary: "#faf4ed",
      bgSecondary: "#fffaf3",
      bgTertiary: "#f2e9e1",
      bgHover: "#e4ddd6",
      textPrimary: "#575279",
      textSecondary: "#6e6a86",
      textMuted: "#9893a5",
      accentPrimary: "#d7827e",
      accentHover: "#ea9a97",
      accentMuted: "#b4637a",
      statusSuccess: "#56949f",
      statusWarning: "#ea9d34",
      statusError: "#b4637a",
      borderPrimary: "#f2e9e1",
      borderSecondary: "#e4ddd6",
      terminalBg: "#faf4ed",
      terminalFg: "#575279",
      terminalCursor: "#575279",
      terminalSelection: "#f2e9e1",
    },
  },
  {
    id: "gruvbox-light",
    name: "Gruvbox Light",
    colors: {
      bgPrimary: "#fbf1c7",
      bgSecondary: "#ebdbb2",
      bgTertiary: "#d5c4a1",
      bgHover: "#c9b99a",
      textPrimary: "#3c3836",
      textSecondary: "#504945",
      textMuted: "#928374",
      accentPrimary: "#d65d0e",
      accentHover: "#fe8019",
      accentMuted: "#af3a03",
      statusSuccess: "#79740e",
      statusWarning: "#b57614",
      statusError: "#cc241d",
      borderPrimary: "#ebdbb2",
      borderSecondary: "#d5c4a1",
      terminalBg: "#fbf1c7",
      terminalFg: "#3c3836",
      terminalCursor: "#3c3836",
      terminalSelection: "#ebdbb2",
    },
  },
  {
    id: "tokyo-night-light",
    name: "Tokyo Night Light",
    colors: {
      bgPrimary: "#d5d6db",
      bgSecondary: "#cbccd1",
      bgTertiary: "#c0c1c6",
      bgHover: "#b4b5ba",
      textPrimary: "#343b58",
      textSecondary: "#4c505e",
      textMuted: "#9699a3",
      accentPrimary: "#34548a",
      accentHover: "#4674b0",
      accentMuted: "#2b446e",
      statusSuccess: "#485e30",
      statusWarning: "#8f5e15",
      statusError: "#8c4351",
      borderPrimary: "#cbccd1",
      borderSecondary: "#c0c1c6",
      terminalBg: "#d5d6db",
      terminalFg: "#343b58",
      terminalCursor: "#343b58",
      terminalSelection: "#c0c1c6",
    },
  },
  {
    id: "everforest-light",
    name: "Everforest Light",
    colors: {
      bgPrimary: "#fdf6e3",
      bgSecondary: "#f4f0d9",
      bgTertiary: "#e5dfc8",
      bgHover: "#d8d3b8",
      textPrimary: "#5c6a72",
      textSecondary: "#708089",
      textMuted: "#a6b0a0",
      accentPrimary: "#8da101",
      accentHover: "#a5b832",
      accentMuted: "#6e8000",
      statusSuccess: "#8da101",
      statusWarning: "#dfa000",
      statusError: "#f85552",
      borderPrimary: "#e5dfc8",
      borderSecondary: "#d8d3b8",
      terminalBg: "#fdf6e3",
      terminalFg: "#5c6a72",
      terminalCursor: "#5c6a72",
      terminalSelection: "#e5dfc8",
    },
  },
  {
    id: "dracula-light",
    name: "Dracula Light",
    colors: {
      bgPrimary: "#f8f8f2",
      bgSecondary: "#eee8e0",
      bgTertiary: "#e2dcd4",
      bgHover: "#d6d0c8",
      textPrimary: "#282a36",
      textSecondary: "#44475a",
      textMuted: "#9fa0b0",
      accentPrimary: "#9b59b6",
      accentHover: "#b06cc8",
      accentMuted: "#7d4798",
      statusSuccess: "#27ae60",
      statusWarning: "#f39c12",
      statusError: "#e74c3c",
      borderPrimary: "#e2dcd4",
      borderSecondary: "#d6d0c8",
      terminalBg: "#f8f8f2",
      terminalFg: "#282a36",
      terminalCursor: "#282a36",
      terminalSelection: "#e2dcd4",
    },
  },
];

const CSS_VAR_MAP: Record<keyof ThemeColors, string> = {
  bgPrimary: "--bg-primary",
  bgSecondary: "--bg-secondary",
  bgTertiary: "--bg-tertiary",
  bgHover: "--bg-hover",
  textPrimary: "--text-primary",
  textSecondary: "--text-secondary",
  textMuted: "--text-muted",
  accentPrimary: "--accent-primary",
  accentHover: "--accent-hover",
  accentMuted: "--accent-muted",
  statusSuccess: "--status-success",
  statusWarning: "--status-warning",
  statusError: "--status-error",
  borderPrimary: "--border-primary",
  borderSecondary: "--border-secondary",
  terminalBg: "--terminal-bg",
  terminalFg: "--terminal-fg",
  terminalCursor: "--terminal-cursor",
  terminalSelection: "--terminal-selection",
};

export function applyThemeCssVars(theme: ThemeDefinition): void {
  const root = document.documentElement;
  for (const [key, cssVar] of Object.entries(CSS_VAR_MAP)) {
    root.style.setProperty(cssVar, theme.colors[key as keyof ThemeColors]);
  }
}

export function getThemeById(id: string): ThemeDefinition | undefined {
  return THEMES.find((t) => t.id === id);
}
